program RigmMovieTests;
{$APPTYPE CONSOLE}
uses System.SysUtils, System.Classes, System.IOUtils, System.JSON, System.Math, Winapi.Windows, Vcl.Graphics,
  RigmMovieModel, RigmMovieAudio, RigmMovieRendering, RigmMovieAvi,
  RigmMovieSession, RigmMovieActing, RigmMoviePreparation, RigmModel, RigmJson, RigmSample, ArtDocument, RigmStorage, System.Hash, System.Generics.Collections;
var Checks: TJSONArray; Root: string;
procedure Check(Condition: Boolean; const Name: string);
begin if not Condition then raise Exception.Create(Name); Checks.Add(Name); Writeln('PASS: '+Name); end;
function HasIssue(O: TJSONObject; const Code: string): Boolean;
begin Result := False; for var V in JA(O,'issues') do if JS(TJSONObject(V),'code')=Code then Exit(True); end;
procedure PreparationTests;
var P,Q: TRigmMovieProject; D,J,O: TJSONObject; Doc: TRigmDocument; Audio: TRigmPcm;
begin
  P := TRigmMovieProject.Create; Q := nil; D := TJSONObject.Create; J := ParseObject('{"done":true,"state":"none"}'); Doc := nil; Audio := nil;
  try
    var Before := P.Json; var Revision := P.Revision;
    O := MoviePreparation(P,D,J);
    try
      Check(JB(O,'readOnly') and not JB(O,'realSpeechVerified'),'preparation explicitly limits read-only and speech verification scope');
      Check(HasIssue(O,'script_empty') and HasIssue(O,'engine_unchecked') and HasIssue(O,'output_missing'),'first use identifies missing script engine and target');
      Check((JA(O,'steps').Count=5) and (JS(O,'nextCommand')='movie-import-script'),'first use has five ordered steps and concrete next command');
      Check(not JB(O,'canGenerateAudio') and not JB(O,'canExport'),'first use does not claim preparation complete');
    finally O.Free; end;
    var After := P.Json;
    try Check((Before.ToJSON=After.ToJSON) and (P.Revision=Revision) and not P.Modified,'read-only diagnosis preserves empty project and revision'); finally Before.Free; After.Free; end;
    P.Free; P := TRigmMovieProject.FromText('narrator:explicit test fixture script');
    P.CharacterFile := '@sample'; P.OutputTarget := TPath.Combine(Root,'prepared.avi');
    D.AddPair('key',MoviePreparationKey(P)); AddB(D,'engineConnected',True); D.AddPair('speakers',TJSONObject.ParseJSONValue('[{"styleId":101,"name":"TEST TONE","style":"FIXTURE"}]') as TJSONArray);
    Doc := TRigmDocument.Create; PopulateRigmSample(Doc); var Assets := MovieActorAssets(Doc); Assets.AddPair('capabilities',MovieCapabilities(Doc)); D.AddPair('assets',Assets);
    O := MoviePreparation(P,D,J);
    try
      Check(HasIssue(O,'speaker_unavailable') and HasIssue(O,'audio_pending'),'available engine still requires actual speaker allocation and audio');
      Check(JS(O,'nextAction')='movie-update-speaker','speaker allocation precedes audio generation');
      Check(not JB(JO(O,'capabilities'),'naturalFaceDirections'),'preparation does not fabricate unsupported face directions');
      Check(JB(JO(O,'capabilities'),'headBodyMotion') and not JB(JO(O,'capabilities'),'mouthAssets'),'sample capabilities distinguish deformation from absent expression assets');
      Check(JN(JO(O,'estimate'),'freeBytes')>0,'read-only preparation measures existing output drive free capacity');
    finally O.Free; end;
    P.Speaker('narrator').StyleId := 101;
    O := MoviePreparation(P,D,J); try Check(JB(O,'canGenerateAudio') and (JS(O,'nextAction')='movie-audio-generate'),'allocated available speaker permits generation'); finally O.Free; end;
    P.Speaker('narrator').StyleId := 999;
    O := MoviePreparation(P,D,J); try Check(HasIssue(O,'speaker_unavailable') and not JB(O,'canGenerateAudio'),'unavailable catalog style prevents generation'); finally O.Free; end;
    P.Speaker('narrator').StyleId := 101;
    Audio := TRigmPcm.Create; Audio.Rate := 24000; SetLength(Audio.Samples,12000); Audio.Save(TPath.Combine(Root,'preparation-tone.wav'));
    var C := P.Cues[0]; C.WaveFile := TPath.Combine(Root,'preparation-tone.wav'); C.AudioSeconds := 0.5; C.AudioKey := P.AudioFingerprint(C);
    D.RemovePair('engineConnected').Free; AddB(D,'engineConnected',False); D.AddPair('engineError','explicit disconnected fixture');
    O := MoviePreparation(P,D,J,'',True);
    try Check(HasIssue(O,'engine_unavailable') and JB(O,'canExport') and (JS(O,'nextAction')='movie-export'),'saved ready audio can export while engine is disconnected'); finally O.Free; end;
    D.AddPair('actingError','explicit absent asset fixture');
    O := MoviePreparation(P,D,J);
    try
      Check(HasIssue(O,'acting_unavailable') and not JB(O,'canExport'),'incompatible acting blocks export with specific issue');
      Check((JS(O,'nextCommand')='movie-update-cue') and (JS(JO(JO(O,'nextArgs'),'acting'),'mouthMode')='auto'),'safe acting guidance supplies actual pipe command and arguments');
    finally O.Free; end;
    D.RemovePair('actingError').Free;
    O := MoviePreparation(P,D,J,TPath.Combine(Root,'fixture-tone.wav'));
    try Check(HasIssue(O,'output_exists') and not JB(O,'canExport'),'preparation refuses existing output without modifying it'); finally O.Free; end;
    O := MoviePreparation(P,D,J,TPath.Combine(Root,'invalid.txt')); try Check(HasIssue(O,'output_format'),'unsupported output extension has machine-readable issue'); finally O.Free; end;
    O := MoviePreparation(P,D,J,TPath.Combine(Root,'prepared.mp4')); try Check(HasIssue(O,'ffmpeg_missing') and not JB(O,'canExport'),'MP4 requires configured existing FFmpeg'); finally O.Free; end;
    C.Background := TPath.Combine(Root,'absent.png'); O := MoviePreparation(P,D,J);
    try Check(HasIssue(O,'background_missing') and not JB(O,'canPreview'),'missing background blocks preview and export'); finally O.Free; end; C.Background := '';
    P.CharacterFile := TPath.Combine(Root,'missing.rigm'); O := MoviePreparation(P,D,J);
    try Check(not JB(O,'diagnosticsCurrent') and HasIssue(O,'material_unchecked'),'character change invalidates cached material diagnosis'); finally O.Free; end;
    D.RemovePair('key').Free; D.AddPair('key',MoviePreparationKey(P)); D.AddPair('materialError','explicit absent material');
    O := MoviePreparation(P,D,J); try Check(HasIssue(O,'material_invalid') and not JB(O,'canExport'),'failed material reference is actionable and blocks export'); finally O.Free; end;
    D.RemovePair('materialError').Free; P.CharacterFile := '';
    O := MoviePreparation(P,D,J); try Check(HasIssue(O,'character_none') and JB(O,'canExport'),'subtitle-only production is explicitly allowed without character'); finally O.Free; end;
    for var Letter := 'Z' downto 'D' do if not DirectoryExists(Letter+':\') then begin
      O := MoviePreparation(P,D,J,Letter+':\prepared.avi');
      try Check(HasIssue(O,'output_drive_unavailable') or HasIssue(O,'output_path_invalid'),'unavailable output drive is not reported ready'); finally O.Free; end; Break;
    end;
    P.CharacterFile := '@sample'; SaveMovie(P,TPath.Combine(Root,'preparation.rigmovie')); var FileHash := THashSHA2.GetHashStringFromFile(P.FileName); Q := LoadMovie(P.FileName);
    Check(Q.OutputTarget=P.OutputTarget,'save reopen preserves intended new output path');
    O := MoviePreparation(P,D,J); O.Free;
    Check((THashSHA2.GetHashStringFromFile(P.FileName)=FileHash) and not P.Modified,'diagnosis never autosaves or marks saved project dirty');
    var Examples := MovieExamples;
    try
      Check((Examples.Count=2) and (JS(TJSONObject(Examples[0]),'kind')='fictional_example'),'short application example is identified as fictional');
      Check((JS(TJSONObject(Examples[1]),'kind')='structure_template') and not JB(TJSONObject(Examples[1]),'durationGuaranteed'),'three minute example is an explicit non-guaranteed structure template');
      Check(P.Cues[0].Text='explicit test fixture script','reading examples does not replace authored script');
    finally Examples.Free; end;
    var OldKey := MoviePreparationKey(P); P.Cues[0].Acting.MouthMode := 'assets';
    Check(MoviePreparationKey(P)<>OldKey,'feature mode change invalidates cached acting diagnosis');
  finally Audio.Free; Doc.Free; J.Free; D.Free; Q.Free; P.Free; end;
end;
procedure Tests;
var P,Q: TRigmMovieProject; C: TRigmMovieCue; O: TJSONObject; Audio,Mixed: TRigmPcm;
  Doc: TRigmDocument; Pose: TRigmPose; Bitmap: TBitmap; Writer: TRigmMovieAvi; B: TBytes;
  Local,Start: Double; Bad: Boolean;
begin
  P := TRigmMovieProject.FromText('# 自作サンプル'+sLineBreak+'案内:こんにちは。'+sLineBreak+'物語を紹介します。');
  Q := nil; Audio := nil; Mixed := nil; Doc := nil; Pose := nil; Bitmap := nil; Writer := nil;
  try
    Check(P.Cues.Count=2,'text creates two editable cues'); Check(P.Cues[0].Scene='自作サンプル','scene heading preserved');
    Check(P.Speakers.Count=2,'text speaker has stable mapping'); Check(P.Cues[1].SpeakerId='narrator','plain line uses narrator');
    Check(P.Cues[0].Subtitle='こんにちは。','subtitle defaults to original dialogue');
    var CaptionBitmap := TBitmap.Create;
    try
      CaptionBitmap.SetSize(640,360); CaptionBitmap.Canvas.Font.Name := 'Yu Gothic UI'; CaptionBitmap.Canvas.Font.Size := 14;
      var LongCaption := StringOfChar('あ',100)+'終わり'; var Pages: Integer;
      var FirstPage := MovieSubtitlePage(LongCaption,CaptionBitmap.Canvas,220,2,0,Pages);
      Check(Pages>2,'long Japanese subtitle splits into readable bounded pages');
      var Rebuilt := ''; var N := Pages;
      for var I := 0 to N-1 do Rebuilt := Rebuilt+MovieSubtitlePage(LongCaption,CaptionBitmap.Canvas,220,2,I/N,Pages).Replace(sLineBreak,'');
      Check(Rebuilt=LongCaption,'subtitle pagination preserves every Japanese character');
      Check(MovieSubtitlePage(LongCaption,CaptionBitmap.Canvas,220,2,0.99,Pages)<>FirstPage,'later cue timing displays later subtitle page');
      var Emoji := #$D83D#$DE00;
      var Page := MovieSubtitlePage('あ'+Emoji+'い',CaptionBitmap.Canvas,1,1,0.34,Pages);
      Check(Page=Emoji,'subtitle wrapping preserves UTF16 surrogate pairs');
    finally CaptionBitmap.Free; end;
    Check(P.Speaker('案内').StyleId=-1,'voice style stays unselected until real catalog selection');
    O := P.Json; try Q := TRigmMovieProject.FromJson(O); finally O.Free; end;
    Check(Q.Cues[0].Id=P.Cues[0].Id,'JSON roundtrip keeps cue ID'); Check(Q.Title=P.Title,'JSON roundtrip keeps title'); Q.Free; Q := nil;
    Bad := False; O := P.Json; try O.RemovePair('width').Free; AddN(O,'width',321); try Q := TRigmMovieProject.FromJson(O); except Bad := True; end; finally O.Free; end;
    Check(Bad,'odd video width rejected');
    O := P.Json; Bad := False; try O.RemovePair('engineUrl').Free; O.AddPair('engineUrl','http://example.com:50021'); try Q := TRigmMovieProject.FromJson(O); except Bad := True; end; finally O.Free; end;
    Check(Bad,'external engine URL rejected before speech leaves machine');
    P.Width := 320; P.Height := 180; P.Fps := 10; P.Cues.Delete(1); C := P.Cues[0]; C.Pause := 0.2;
    Audio := TRigmPcm.Create; Audio.Rate := 24000; SetLength(Audio.Samples,12000);
    for var I := 0 to High(Audio.Samples) do Audio.Samples[I] := Round(Sin(I*2*Pi*220/Audio.Rate)*10000);
    Audio.Save(TPath.Combine(Root,'fixture-tone.wav')); C.WaveFile := TPath.Combine(Root,'fixture-tone.wav');
    C.AudioSeconds := Audio.Duration; C.AudioKey := P.AudioFingerprint(C);
    Check(P.AudioReady(C),'matching settings and existing WAV mark ready');
    Q := P.Clone; Q.Cues[0].Text := '変えました'; Check(not Q.AudioReady(Q.Cues[0]),'text edit invalidates cached audio'); Q.Free; Q := nil;
    Q := P.Clone; Q.Speaker(C.SpeakerId).Speed := 1.2; Check(not Q.AudioReady(Q.Cues[0]),'speed edit invalidates cached audio'); Q.Free; Q := nil;
    Q := P.Clone; Q.Cues[0].Subtitle := '別字幕'; Check(Q.AudioReady(Q.Cues[0]),'subtitle edit retains valid speech'); Q.Free; Q := nil;
    Check(SameValue(P.Duration,0.7),'timeline derives exact WAV plus pause');
    Check(P.CueAt(0.6,Local,Start)=C,'pause belongs to same cue'); Check(P.CueAt(0.7,Local,Start)=nil,'end boundary has no cue');
    Check(Audio.Envelope(0.1)>0.5,'waveform drives mouth envelope'); Check(Audio.Envelope(0.6)=0,'audio tail closes mouth');
    Mixed := MixMovieAudio(P); Check(Mixed.Rate=48000,'mix resamples to fixed PCM clock');
    Check(Length(Mixed.Samples)=33600,'mix duration includes silence'); Check(Mixed.Samples[30000]=0,'pause remains digital silence');
    Mixed.Save(TPath.Combine(Root,'mixed.wav')); var Loaded := TRigmPcm.Load(TPath.Combine(Root,'mixed.wav'));
    try Check(Length(Loaded.Samples)=Length(Mixed.Samples),'WAV readback sample count exact'); Check(Loaded.Samples[200]=Mixed.Samples[200],'WAV readback amplitude exact'); finally Loaded.Free; end;
    SaveMovie(P,TPath.Combine(Root,'sample.rigmovie')); Q := LoadMovie(P.FileName);
    Check(Q.AudioReady(Q.Cues[0]),'save reopen keeps audio readiness'); Check(not P.Modified,'successful save clears dirty'); Q.Free; Q := nil;
    Doc := TRigmDocument.Create; PopulateRigmSample(Doc); Pose := TRigmPose.Create;
    C.Acting.MouthMode := 'assets'; Bad := False;
    try MoviePose(P,Doc,0.1,Mixed,Pose); except Bad := True; end;
    Check(Bad,'explicit asset animation rejects character without existing mouth variants');
    C.Acting.MouthMode := 'auto';
    MoviePose(P,Doc,0.1,Mixed,Pose); Check(Pose.Value('mouthOpen')>0.5,'timeline pose uses actual voice amplitude');
    MoviePose(P,Doc,0.6,Mixed,Pose); Check(Pose.Value('mouthOpen')=0,'pause pose closes mouth');
    C.Parameters.AddPair('headAngle',TJSONNumber.Create(999)); MoviePose(P,Doc,0.1,Mixed,Pose);
    Check(Pose.Value('headAngle')=30,'manual parameter is clamped to character limits'); C.Parameters.RemovePair('headAngle').Free;
    C.Acting.MouthGain := 0; C.Acting.HeadGain := 0; C.Acting.BodyGain := 0; C.Acting.BlinkStrength := 0;
    MoviePose(P,Doc,0.1,Mixed,Pose);
    Check((Pose.Value('mouthOpen')=0) and (Pose.Value('headAngle')=0) and (Pose.Value('bodyAngle')=0),'acting zero strengths stop independent mouth head and body');
    C.Acting.Onset := 0.1; C.Acting.Duration := 0.3; C.Acting.FadeIn := 0.1; C.Acting.FadeOut := 0.1;
    Check((C.Acting.Gain(0.05,0.7)=0) and SameValue(C.Acting.Gain(0.15,0.7),0.5) and SameValue(C.Acting.Gain(0.35,0.7),0.5) and (C.Acting.Gain(0.4,0.7)=0),'acting cue-local onset duration and fades define bounded window');
    Q := P.Clone; Check(SameValue(Q.Cues[0].Acting.FadeIn,0.1) and (Q.Cues[0].Acting.HeadGain=0),'acting roundtrip preserves timing and strengths'); Q.Free; Q := nil;
    var Stamp := MovieAudioStamp(P); C.Subtitle := '字幕だけ変更'; C.Acting.MouthGain := 1;
    Check((MovieAudioStamp(P)=Stamp) and P.AudioReady(C),'acting and subtitle edits preserve audio stamp and real voice cache');
    C.Pause := 0.3; Check(MovieAudioStamp(P)<>Stamp,'pause edit invalidates mix and waveform stamp'); C.Pause := 0.2;
    var Wave := MovieWaveform(P,128);
    try
      Check((JI(Wave,'sampleCount')=33600) and (JA(Wave,'peaks').Count=128),'waveform bins cover every real PCM sample');
      var LastPeak := TJSONArray(JA(Wave,'peaks')[127]); Check((TJSONNumber(LastPeak[0]).AsInt=0) and (TJSONNumber(LastPeak[1]).AsInt=0),'waveform pause bins remain silent');
    finally Wave.Free; end;
    C.Acting.Free; C.Acting := TRigmMovieActing.Create;
    var Mouth: TArtLayer := nil;
    for var L in Doc.Layers do if Doc.Part(L.Id).Role='mouth' then Mouth := L;
    var Group := Doc.Art.AddLayer(alkGroup,'実在口素材',Mouth.Bounds); Doc.SyncParts; Doc.ReparentLayer(Mouth.Id,Group.Id,0);
    var Alternate := Doc.Art.AddLayer(alkImage,'試験用の実在口候補',Mouth.Bounds); Alternate.Pixels := Copy(Mouth.Pixels);
    for var I := 0 to Length(Alternate.Pixels) div 4-1 do Alternate.Pixels[I*4] := 250;
    Alternate.Visible := False; Doc.SyncParts; Doc.Part(Alternate.Id).Role := 'mouth';
    Doc.ReparentLayer(Alternate.Id,Group.Id,1); Doc.Part(Alternate.Id).X := Doc.Part(Mouth.Id).X; Doc.Part(Alternate.Id).Y := Doc.Part(Mouth.Id).Y;
    Doc.ReparentLayer(Group.Id,'',4);
    Doc.Part(Alternate.Id).BoneId := Doc.Part(Mouth.Id).BoneId; Doc.GenerateMesh(Alternate.Id,Doc.Part(Alternate.Id).BoneId,3);
    O := MovieActorAssets(Doc);
    try Check((JA(O,'groups').Count=1) and (JA(TJSONObject(JA(O,'groups')[0]),'children').Count=2),'asset catalog exposes only existing stored group children'); finally O.Free; end;
    SaveRigm(Doc,TPath.Combine(Root,'actual-variants.rigm')); var SourceHash := THashSHA2.GetHashStringFromFile(TPath.Combine(Root,'actual-variants.rigm'));
    O := ParseObject('{"groupId":"'+Group.Id+'","partId":"'+Alternate.Id+'"}'); C.Acting.Variants.AddElement(O);
    MoviePose(P,Doc,0.1,Mixed,Pose);
    Check(Pose.PartVisibility[Alternate.Id] and not Pose.PartVisibility[Mouth.Id],'acting selects existing hidden variant and hides its sibling at runtime');
    Check(Mouth.Visible and not Alternate.Visible and (THashSHA2.GetHashStringFromFile(TPath.Combine(Root,'actual-variants.rigm'))=SourceHash),'variant preview preserves stored visibility and RIGM bytes');
    O := TJSONObject(C.Acting.Variants[0]); O.RemovePair('partId').Free; O.AddPair('partId','missing-part'); Bad := False;
    try MoviePose(P,Doc,0.1,Mixed,Pose); except Bad := True; end;
    Check(Bad,'nonexistent acting asset is rejected explicitly'); C.Acting.Variants.Free; C.Acting.Variants := TJSONArray.Create;
    var OriginalFrame := RenderMovieFrame(P,Doc,0.1,Mixed);
    try OriginalFrame.SaveToFile(TPath.Combine(Root,'variant-original.bmp')); finally OriginalFrame.Free; end;
    C.Acting.Variants.AddElement(ParseObject('{"groupId":"'+Group.Id+'","partId":"'+Alternate.Id+'"}'));
    var AlternateFrame := RenderMovieFrame(P,Doc,0.1,Mixed);
    try AlternateFrame.SaveToFile(TPath.Combine(Root,'variant-alternate.bmp')); finally AlternateFrame.Free; end;
    Check(THashSHA2.GetHashStringFromFile(TPath.Combine(Root,'variant-original.bmp'))<>THashSHA2.GetHashStringFromFile(TPath.Combine(Root,'variant-alternate.bmp')),'renderer actually displays chosen existing variant pixels');
    var Outer := Doc.Art.AddLayer(alkGroup,'入れ子素材',Group.Bounds); Doc.SyncParts; Doc.ReparentLayer(Group.Id,Outer.Id,0);
    var Other := Doc.Art.AddLayer(alkGroup,'別候補',Group.Bounds); Doc.SyncParts; Doc.ReparentLayer(Other.Id,Outer.Id,1);
    C.Acting.Variants.AddElement(ParseObject('{"groupId":"'+Outer.Id+'","partId":"'+Other.Id+'"}')); Bad := False;
    try MoviePose(P,Doc,0.1,Mixed,Pose); except Bad := True; end;
    Check(Bad,'conflicting nested variant choices are rejected rather than rendering both branches');
    C.Acting.Variants.Free; C.Acting.Variants := TJSONArray.Create;
    Bitmap := RenderMovieFrame(P,Doc,0.1,Mixed); Bitmap.SaveToFile(TPath.Combine(Root,'frame.bmp'));
    Check((Bitmap.Width=320) and (Bitmap.Height=180),'frame has exact project dimensions'); Bitmap.Free; Bitmap := nil;
    Writer := TRigmMovieAvi.Create(TPath.Combine(Root,'short-tone.avi'),320,180,10,7);
    for var I := 0 to 6 do begin Bitmap := RenderMovieFrame(P,Doc,I/10,Mixed); try Writer.AddFrame(Bitmap,Mixed); finally Bitmap.Free; Bitmap := nil; end; end;
    Writer.Finish; Writer.Free; Writer := nil; B := TFile.ReadAllBytes(TPath.Combine(Root,'short-tone.avi'));
    Check(TEncoding.ASCII.GetString(B,0,4)='RIFF','video is RIFF container'); Check(TEncoding.ASCII.GetString(B,8,4)='AVI ','AVI signature valid');
    var RiffSize: Cardinal; Move(B[4],RiffSize,4); Check(RiffSize=Length(B)-8,'final AVI size patched exactly');
    Check(Length(B)>10000,'AVI contains nonempty frames and PCM');
    Bad := False; var Invalid := TPath.Combine(Root,'invalid.wav'); TFile.WriteAllText(Invalid,'broken');
    try var Broken := TRigmPcm.Load(Invalid); Broken.Free; except Bad := True; end;
    Check(Bad,'broken WAV rejected instead of fabricated duration');
  finally Writer.Free; Bitmap.Free; Pose.Free; Doc.Free; Mixed.Free; Audio.Free; Q.Free; P.Free; end;
end;
procedure LongAudioTests;
var P: TRigmMovieProject; Source,Mixed: TRigmPcm;
begin
  P := TRigmMovieProject.FromText('narrator:long audio fixture'); Source := TRigmPcm.Create; Mixed := nil;
  try
    for var Rate in [24000,48000] do begin
      Source.Rate := Rate; SetLength(Source.Samples,Rate*3);
      for var I := 0 to High(Source.Samples) do Source.Samples[I] := 1234;
      var C := P.Cues[0]; C.Pause := 0.2; C.AudioSeconds := 3;
      C.WaveFile := TPath.Combine(Root,'long-tone-'+Rate.ToString+'.wav'); Source.Save(C.WaveFile); C.AudioKey := P.AudioFingerprint(C);
      Mixed := MixMovieAudio(P);
      Check(Length(Mixed.Samples)=153600,'three-second '+Rate.ToString+' Hz mix keeps exact duration');
      Check((Mixed.Samples[48000]=1234) and (Mixed.Samples[100000]=1234) and (Mixed.Samples[143999]=1234),'long '+Rate.ToString+' Hz audio retains samples beyond former integer overflow');
      Check((Mixed.Samples[144000]=0) and (Mixed.Samples[153599]=0),'long '+Rate.ToString+' Hz audio preserves following silence');
      FreeAndNil(Mixed);
    end;
  finally Mixed.Free; Source.Free; P.Free; end;
end;
procedure SessionTests;
var Session: TRigmMovieSession; Reply,O: TJSONObject; Bad: Boolean; Revision: Integer;
  function Command(const Name,Json: string; Mutating: Boolean=False): TJSONObject;
  var A: TJSONObject;
  begin
    A := ParseObject(Json);
    try
      if Mutating then begin A.AddPair('projectId',Session.Project.Id); AddN(A,'revision',Session.Project.Revision); end;
      Result := Session.Execute(Name,A);
    finally A.Free; end;
  end;
begin
  Session := TRigmMovieSession.Create; Reply := nil; O := nil;
  try
    Reply := Command('schema','{}'); Check(JO(Reply,'commands').Count=64,'movie API declares 64 commands'); FreeAndNil(Reply);
    Reply := Command('update-project','{"outputPreset":"fullhd","encodeProfile":"fast"}',True); FreeAndNil(Reply);
    Check((Session.Project.Width=1920) and (Session.Project.Height=1080) and (Session.Project.Fps=30) and (Session.Project.EncodeProfile='fast'),'pipe preset applies full HD dimensions and speed choice');
    Reply := Command('update-project','{"width":800}',True); FreeAndNil(Reply);
    var SettingsJson := Session.Project.Json;
    try Check((JS(SettingsJson,'outputPreset')='custom') and (JS(SettingsJson,'encodeProfile')='fast'),'manual dimensions become custom without discarding encoding choice'); finally SettingsJson.Free; end;
    Revision := Session.Project.Revision; Bad := False;
    try Reply := Command('update-project','{"encodeProfile":"unknown"}',True); except Bad := True; end;
    Check(Bad and (Session.Project.Revision=Revision) and (Session.Project.EncodeProfile='fast'),'invalid encoding choice rolls back full mutation');
    Reply := Command('update-project','{"outputPreset":"hd","encodeProfile":"balanced"}',True); FreeAndNil(Reply);
    Reply := Command('import-script','{"text":"案内:こんにちは。"}',True); FreeAndNil(Reply);
    Check(Session.Project.Cues.Count=1,'API imports editable dialogue');
    Revision := Session.Project.Revision; Bad := False;
    try Reply := Command('update-project','{"width":321}',True); except Bad := True; end;
    Check(Bad and (Session.Project.Width=1280) and (Session.Project.Revision=Revision),'invalid update rolls back entire project and revision');
    Reply := Command('update-project','{"title":"独立テスト","character":"@sample","width":320,"height":180,"fps":10}',True); FreeAndNil(Reply);
    Reply := Command('undo','{}',True); FreeAndNil(Reply); Check(Session.Project.Width=1280,'movie undo restores earlier settings');
    Reply := Command('redo','{}',True); FreeAndNil(Reply); Check(Session.Project.Width=320,'movie redo reapplies settings');
    Reply := Command('preview','{"time":0.1}'); FreeAndNil(Reply);
    var Deadline := GetTickCount64+10000;
    while Session.Busy and (GetTickCount64<Deadline) do Sleep(5);
    Session.Poll; Reply := Command('job-status','{}'); Check(JS(Reply,'state')='succeeded','background character subtitle preview succeeds'); FreeAndNil(Reply);
    var Frame := Session.TakeFrame; try Check((Frame<>nil) and (Frame.Width=320),'completed frame transferred after job only'); finally Frame.Free; end;
    Reply := Command('update-project','{"engineUrl":"http://127.0.0.1:65534"}',True); FreeAndNil(Reply);
    Reply := Command('speakers-refresh','{}'); FreeAndNil(Reply); Deadline := GetTickCount64+10000;
    while Session.Busy and (GetTickCount64<Deadline) do Sleep(5);
    Session.Poll; Reply := Command('job-status','{}');
    Check(JS(Reply,'state')='failed','unavailable real engine reports failed job'); Check(JS(Reply,'error')<>'','failed connection retains actionable error'); FreeAndNil(Reply);
    Check(Session.Project.Cues[0].Text='こんにちは。','failed engine does not damage script');
    O := TJSONObject.Create; O.AddPair('projectId','stale'); AddN(O,'revision',0); Bad := False;
    try Reply := Session.Execute('delete-cue',O); except Bad := True; end;
    Check(Bad and (Session.Project.Cues.Count=1),'stale project identity cannot delete dialogue');
  finally O.Free; Reply.Free; Session.Free; end;
end;
begin
  Checks := TJSONArray.Create; Root := TPath.Combine(ExtractFilePath(ParamStr(0)),'Movie\'+FormatDateTime('yyyymmdd-hhnnss-zzz',Now)); ForceDirectories(Root);
  try
    try Tests; LongAudioTests; SessionTests; PreparationTests; var O := TJSONObject.Create; try AddB(O,'success',True); AddN(O,'passed',Checks.Count); O.AddPair('checks',Checks.Clone as TJSONArray);
      O.AddPair('directory',Root);
      TFile.WriteAllText(TPath.Combine(ExtractFilePath(ParamStr(0)),'Movie\results.json'),O.ToJSON,TEncoding.UTF8); finally O.Free; end;
    except on E: Exception do begin Writeln(E.ClassName+': '+E.Message); ExitCode := 1; end; end;
  finally Checks.Free; end;
end.
