program RigmMovieWorkflowTests;
{$APPTYPE CONSOLE}
{$R '..\RIGMMaker.res'}
uses System.SysUtils, System.Classes, System.IOUtils, System.JSON, System.Math,
  System.Hash, System.Generics.Collections, Winapi.Windows, Winapi.Messages, Vcl.Forms, Vcl.Controls, Vcl.StdCtrls, Vcl.ComCtrls,
  Vcl.Graphics, Vcl.ExtCtrls, Vcl.Imaging.pngimage, Vcl.Themes, Vcl.Styles,
  RigmEditorForm, RigmMovieForm, RigmMovieTimeline, RigmAppSettings, RigmMovieModel, RigmMovieAudio, RigmModel,
  RigmJson, RigmStorage, RigmPipeTestClient, ArtDocument, RigmNativeSaveDialog;
var Host: TRigmEditorForm; PipeName,Root,FixtureDirectory,FFmpegExe: string; Checks: TJSONArray;
procedure Check(Value: Boolean; const Name: string);
begin if not Value then raise Exception.Create('FAIL '+Name); Checks.Add(Name); Writeln('PASS: '+Name); end;
function Find(Parent: TWinControl; const Name: string): TControl;
begin Result := nil; for var I := 0 to Parent.ControlCount-1 do begin var C := Parent.Controls[I]; if C.Name=Name then Exit(C); if C is TWinControl then begin Result := Find(TWinControl(C),Name); if Result<>nil then Exit; end; end; end;
function Call(const Command: string; const Json: string='{}'; Mutating: Boolean=False): TJSONObject;
var Args,Reply: TJSONObject;
begin
  Args := ParseObject(Json);
  if Mutating then begin Args.AddPair('projectId',Host.Editor.Movie.Project.Id); AddN(Args,'revision',Host.Editor.Movie.Project.Revision); end;
  Reply := PipeCall(PipeName,'movie-'+Command,Args);
  try if not JB(Reply,'ok') then raise Exception.Create(Reply.ToJSON); Result := JO(Reply,'data').Clone as TJSONObject; finally Reply.Free; end;
end;
procedure Run(const Command: string; const Json: string='{}'; Mutating: Boolean=False);
begin var O := Call(Command,Json,Mutating); O.Free; end;
function Job: TJSONObject;
var Deadline: UInt64;
begin
  Deadline := GetTickCount64+20000;
  repeat
    Application.ProcessMessages; Host.Editor.PollMovie;
    Result := Call('job-status');
    if JB(Result,'done') then begin Host.Editor.PollMovie; if not Host.Editor.Movie.Busy then Exit; end;
    Result.Free;
    Sleep(5);
  until GetTickCount64>Deadline;
  raise Exception.Create('Movie job timeout');
end;
function Diagnostic: TJSONObject;
var Deadline: UInt64;
begin
  Deadline := GetTickCount64+15000;
  repeat
    Application.ProcessMessages; Host.Editor.PollMovie;
    Result := Call('preparation');
    if JB(Result,'diagnosticsCurrent') and not JB(Result,'diagnosticsBusy') then Exit;
    Result.Free; Sleep(5);
  until GetTickCount64>Deadline;
  raise Exception.Create('Current diagnostic timeout');
end;
procedure Capture(Form: TForm; const Name: string);
var Bitmap: Vcl.Graphics.TBitmap; Image: TPngImage;
begin
  Form.Repaint; Application.ProcessMessages; Bitmap := Vcl.Graphics.TBitmap.Create; Image := TPngImage.Create;
  try Bitmap.SetSize(Form.ClientWidth,Form.ClientHeight); Form.PaintTo(Bitmap.Canvas,0,0); Image.Assign(Bitmap); Image.SaveToFile(TPath.Combine(Root,Name+'.png'));
  finally Image.Free; Bitmap.Free; end;
end;
procedure Tests;
var O,A: TJSONObject; Studio: TRigmMovieForm; SourceHash,SourceText,Path: string; C: TRigmMovieCue; Loaded: TRigmMovieProject;
begin
  Host := TRigmEditorForm.Create(nil);
  try
    Host.OpenSample; Host.Show; Application.ProcessMessages;
    var Directory := ''; for var I := 1 to ParamCount do if ParamStr(I).StartsWith('--pipe-dir=') then Directory := ExpandFileName(ParamStr(I).Substring(11));
    var Files := TDirectory.GetFiles(Directory,'RIGMMaker.'+GetCurrentProcessId.ToString+'.*.json');
    Check(Length(Files)=1,'editor publishes original common pipe discovery'); O := ParseObject(TFile.ReadAllText(Files[0],TEncoding.UTF8));
    try PipeName := JS(O,'commandPipe'); finally O.Free; end;
    O := PipeCall(PipeName,'schema',TJSONObject.Create);
    try Check(JS(JO(O,'data'),'movieCommandPrefix')='movie-','common schema advertises movie namespace'); finally O.Free; end;
    O := RigmManifest(Host.Editor.Document); try SourceText := O.ToJSON; finally O.Free; end;
    SourceHash := THashSHA2.GetHashString(SourceText);
    Run('open-ui'); Studio := nil;
    for var I := 0 to Host.ComponentCount-1 do if Host.Components[I] is TRigmMovieForm then Studio := TRigmMovieForm(Host.Components[I]);
    Check((Studio<>nil) and Studio.Visible,'common movie-open-ui opens production screen');
    var FirstUseRevision := Host.Editor.Movie.Project.Revision;
    Check((Host.Editor.Movie.Project.Cues.Count=0) and (TMemo(Find(Studio,'MovieScript')).Text='') and
      (TEdit(Find(Studio,'MovieCueScene')).Text='') and (TMemo(Find(Studio,'MovieCueText')).Text='') and
      (TMemo(Find(Studio,'MovieCueSubtitle')).Text=''),'first use opens empty inputs without generated script or component names');
    var GuideDeadline := GetTickCount64+5000;
    while (TLabel(Find(Studio,'MovieWorkflowGuide')).Caption='') and (GetTickCount64<GuideDeadline) do begin Application.ProcessMessages; Sleep(5); end;
    var GuideLabel := TLabel(Find(Studio,'MovieWorkflowGuide'));
    Writeln(Format('GUIDE width=%d height=%d caption=%s',[GuideLabel.Width,GuideLabel.Height,GuideLabel.Caption]));
    Check((GuideLabel.Caption<>'') and (GuideLabel.Width>500) and not GuideLabel.AutoSize,'workflow guide has explicit visible bounds and current first-use instruction');
    O := Call('preparation');
    try Check(JB(O,'readOnly') and (JA(O,'steps').Count=5) and (JS(O,'nextCommand')='movie-import-script'),'common preparation command exposes read-only first-use guide'); finally O.Free; end;
    Check(Host.Editor.Movie.Project.Revision=FirstUseRevision,'initial read-only guide does not change project revision');
    TButton(Find(Studio,'MovieLoadExample')).Click;
    Check((Host.Editor.Movie.Project.Cues.Count=0) and (Host.Editor.Movie.Project.Revision=FirstUseRevision) and (TMemo(Find(Studio,'MovieScript')).Text<>''),'explicit fictional example enters draft only without importing project');
    TComboBox(Find(Studio,'MovieScriptExample')).ItemIndex := 1; TButton(Find(Studio,'MovieLoadExample')).Click;
    Check((Host.Editor.Movie.Project.Cues.Count=0) and string(TMemo(Find(Studio,'MovieScript')).Text).Contains('0:15'),'explicit structure template enters draft only');
    Capture(Studio,'studio-first-use');
    TMemo(Find(Studio,'MovieScript')).Text := '# 紹介'+sLineBreak+'narrator:これは自作の架空作品の紹介です。'+sLineBreak+'# 総評'+sLineBreak+'narrator:色づかいが好きです。';
    TButton(Find(Studio,'MovieRunStep')).Click; Check(Host.Editor.Movie.Project.Cues.Count=2,'stage result UI imports authored input into shared pipe session');
    var PresetCombo := TComboBox(Find(Studio,'MovieOutputPreset')); var ProfileCombo := TComboBox(Find(Studio,'MovieEncodeProfile'));
    var PresetRevision := Host.Editor.Movie.Project.Revision;
    PresetCombo.ItemIndex := 2; PresetCombo.OnChange(PresetCombo); ProfileCombo.ItemIndex := 0;
    Check((Host.Editor.Movie.Project.Revision=PresetRevision) and string(TEdit(Find(Studio,'MovieDimensions')).Text).Contains('1920'),'preset selection prepares dimensions until settings apply');
    TEdit(Find(Studio,'MovieOutputTarget')).Text := TPath.Combine(Root,'intended-output.avi');
    TButton(Find(Studio,'MovieApplySettings')).Click;
    Check((Host.Editor.Movie.Project.Width=1920) and (Host.Editor.Movie.Project.Height=1080) and (Host.Editor.Movie.Project.Fps=30) and (Host.Editor.Movie.Project.EncodeProfile='fast'),'UI applies full HD and speed profile to common session');
    O := Call('project'); try Check((JS(O,'outputPreset')='fullhd') and (JS(O,'encodeProfile')='fast'),'common pipe exposes UI output preset and encoding choice'); finally O.Free; end;
    Run('update-project','{"outputPreset":"hd","encodeProfile":"quality"}',True); Application.ProcessMessages;
    var SettingsDeadline := GetTickCount64+3000;
    while (ProfileCombo.ItemIndex<>2) and (GetTickCount64<SettingsDeadline) do begin Application.ProcessMessages; Sleep(5); end;
    Check((PresetCombo.ItemIndex=1) and (ProfileCombo.ItemIndex=2),'pipe output changes return to preset and profile UI');
    A := TJSONObject.Create; A.AddPair('path',TPath.Combine(Root,'preset-profile.rigmovie')); Run('save',A.ToJSON); Run('open',A.ToJSON,True); A.Free;
    Check((Host.Editor.Movie.Project.EncodeProfile='quality') and (Host.Editor.Movie.Project.Width=1280),'save reopen preserves output settings');
    Check(Host.Editor.Movie.Project.OutputTarget=TPath.Combine(Root,'intended-output.avi'),'save reopen restores intended output target to production flow');
    Run('update-project','{"encodeProfile":"balanced"}',True);
    Run('update-project','{"character":"@sample","width":640,"height":360,"fps":15,"engineUrl":"http://127.0.0.1:51234"}',True);
    Run('diagnostics-refresh');
    var DiagnosticDeadline := GetTickCount64+5000;
    repeat
      Application.ProcessMessages; O := Call('job-status','{"scope":"diagnostics"}');
      var DiagnosticDone := JB(O,'done'); O.Free; if DiagnosticDone then Break; Sleep(5);
    until GetTickCount64>DiagnosticDeadline;
    O := Diagnostic;
    try Check(JB(O,'diagnosticsCurrent') and JB(JO(O,'engine'),'connected') and (JA(O,'availableStyles').Count=2),'read-only diagnosis obtains actual fixture catalog independently'); finally O.Free; end;
    var DraftEdit := TEdit(Find(Studio,'MovieOutputTarget')); DraftEdit.Text := TPath.Combine(Root,'unapplied-draft.avi');
    var DraftRevision := Host.Editor.Movie.Project.Revision; var DialogueDraft := TMemo(Find(Studio,'MovieCueText')); DialogueDraft.Text := 'unapplied authored dialogue draft';
    Run('diagnostics-refresh'); DiagnosticDeadline := GetTickCount64+5000;
    repeat
      Application.ProcessMessages; O := Call('job-status','{"scope":"diagnostics"}');
      var DiagnosticDone := JB(O,'done'); O.Free; if DiagnosticDone then Break; Sleep(5);
    until GetTickCount64>DiagnosticDeadline;
    var RefreshDeadline := GetTickCount64+300; while GetTickCount64<RefreshDeadline do begin Application.ProcessMessages; Sleep(5); end;
    Check((DraftEdit.Text=TPath.Combine(Root,'unapplied-draft.avi')) and (DialogueDraft.Text='unapplied authored dialogue draft') and (Host.Editor.Movie.Project.Revision=DraftRevision),'diagnosis completion preserves unapplied output and dialogue editors and revision');
    TButton(Find(Studio,'MovieReloadDraft')).Click; // Explicitly discard the already-tested pending input before the next scenario.
    // The explicit reload above restores current data and clears the tested drafts.
    var SpeakerMarker := TPath.Combine(FixtureDirectory,'speakers-active.txt');
    if FileExists(SpeakerMarker) then TFile.Delete(SpeakerMarker);
    var SpeakerDelay := TPath.Combine(FixtureDirectory,'speakers-delay-ms.txt'); TFile.WriteAllText(SpeakerDelay,'1500');
    Run('diagnostics-refresh'); DiagnosticDeadline := GetTickCount64+3000;
    while not FileExists(SpeakerMarker) and (GetTickCount64<DiagnosticDeadline) do begin Application.ProcessMessages; Sleep(5); end;
    Check(FileExists(SpeakerMarker),'diagnosis cancellation reaches actual active catalog HTTP request');
    Check(not Host.Editor.Movie.Busy,'independent diagnosis keeps project editing available');
    Run('update-project','{"title":"authored title during read-only diagnosis"}',True);
    Check(Host.Editor.Movie.Project.Title='authored title during read-only diagnosis','author can commit project settings during diagnosis');
    var CancelStart := GetTickCount64; Run('job-cancel','{"scope":"diagnostics"}'); var CancelReply := GetTickCount64-CancelStart;
    repeat
      Application.ProcessMessages; O := Call('job-status','{"scope":"diagnostics"}'); var DiagnosticDone := JB(O,'done'); O.Free;
      if DiagnosticDone then Break; Sleep(5);
    until GetTickCount64>CancelStart+800;
    O := Call('job-status','{"scope":"diagnostics"}');
    try Check((JS(O,'state')='cancelled') and (CancelReply<200) and (GetTickCount64-CancelStart<800),'diagnosis cancellation preserves original UI response bounds'); finally O.Free; end;
    TFile.Delete(SpeakerDelay); Run('diagnostics-refresh'); O := Diagnostic; O.Free;
    Run('speakers-refresh'); O := Job;
    try Check(JS(O,'state')='succeeded','copied catalog reads deterministic local HTTP fixture'); finally O.Free; end;
    O := Call('speaker-list'); try Check(JA(O,'styles').Count=2,'speaker style IDs exposed through common pipe'); finally O.Free; end;
    Run('update-speaker','{"id":"narrator","styleId":101,"speed":1.1}',True);
    Run('audio-generate',ParseObject('{"directory":"'+Root.Replace('\','\\')+'\\Audio"}').ToJSON); O := Job;
    try Check(JS(O,'state')='succeeded','copied audio_query synthesis WAV LAB chain works with explicitly marked tone fixture'); finally O.Free; end;
    Check(Host.Editor.Movie.Project.AudioReady(Host.Editor.Movie.Project.Cues[0]) and Host.Editor.Movie.Project.AudioReady(Host.Editor.Movie.Project.Cues[1]),'generated cues become ready without fabricated speech');
    O := Call('preparation'); try Check(JB(O,'canPreview') and (JI(O,'audioPending')=0),'generated audio advances preparation readiness'); finally O.Free; end;
    A := TJSONObject.Create; A.AddPair('id',Host.Editor.Movie.Project.Cues[0].Id); A.AddPair('acting',ParseObject('{"mouthMode":"assets"}')); Run('update-cue',A.ToJSON,True); A.Free;
    Run('diagnostics-refresh'); O := Diagnostic;
    try
      var ActingUnavailable := False; for var V in JA(O,'issues') do if JS(TJSONObject(V),'code')='acting_unavailable' then ActingUnavailable := True;
      Check(ActingUnavailable and not JB(O,'canExport'),'diagnosis checks actual absent mouth assets before export');
    finally O.Free; end;
    TButton(Find(Studio,'MovieSafeActing')).Click;
    Check((Host.Editor.Movie.Project.Cues[0].Acting.MouthMode='auto') and Host.Editor.Movie.Project.AudioReady(Host.Editor.Movie.Project.Cues[0]),'safe acting UI restores available method without regenerating audio');
    Check(FileExists(Host.Editor.Movie.Project.Cues[0].LabFile),'existing library produces phoneme LAB');
    Check(SameValue(Host.Editor.Movie.Project.Duration,1.6),'two 0.5 second WAV cues and pauses define exact timeline');
    var WaveButton := TToolButton(Find(Studio,'MovieWaveform')); WaveButton.OnClick(WaveButton); O := Job;
    try Check(JS(O,'state')='succeeded','waveform icon starts actual PCM waveform worker'); finally O.Free; end;
    O := Call('waveform');
    try Check(JB(O,'current') and (JI(O,'sampleCount')=76800) and (JA(O,'peaks').Count=2048),'common pipe exposes current bounded waveform with exact timeline sample count'); finally O.Free; end;
    TEdit(Find(Studio,'MovieActing_mouthGain')).Text := '0.6'; TEdit(Find(Studio,'MovieActing_headGain')).Text := '0.8';
    TEdit(Find(Studio,'MovieActing_blinkInterval')).Text := '1.5'; TEdit(Find(Studio,'MovieActing_fadeIn')).Text := '0.1';
    TComboBox(Find(Studio,'MovieMouthMode')).ItemIndex := 2; TComboBox(Find(Studio,'MovieBlinkMode')).ItemIndex := 2;
    TButton(Find(Studio,'MovieApplyActing')).Click;
    Check((Host.Editor.Movie.Project.Cues[0].Acting.MouthMode='deform') and (Host.Editor.Movie.Project.Cues[0].Acting.BlinkMode='deform'),'acting mode UI commits both feature choices');
    Check(SameValue(Host.Editor.Movie.Project.Cues[0].Acting.MouthGain,0.6) and SameValue(Host.Editor.Movie.Project.Cues[0].Acting.HeadGain,0.8),'acting UI applies selected cue strengths');
    Check(SameValue(Host.Editor.Movie.Project.Cues[0].Acting.BlinkInterval,1.5) and SameValue(Host.Editor.Movie.Project.Cues[0].Acting.FadeIn,0.1),'acting UI applies blink and timing');
    var ActingScroll := TScrollBox(Find(Studio,'MovieApplyActing').Parent); ActingScroll.VertScrollBar.Position := 590;
    Capture(Studio,'studio-acting-controls'); Check(Find(Studio,'MovieApplyActing').Top>=0,'acting controls scroll into accessible viewport'); ActingScroll.VertScrollBar.Position := 0;
    Check(Host.Editor.Movie.Project.Modified and Host.Editor.Movie.Project.AudioReady(Host.Editor.Movie.Project.Cues[0]),'acting edit becomes unsaved while preserving generated voice');
    O := Call('waveform'); try Check(JB(O,'current'),'acting-only revision retains valid waveform'); finally O.Free; end;
    Application.ProcessMessages; while Host.Editor.Movie.Busy or Studio.PreviewPending do begin Application.ProcessMessages; Host.Editor.PollMovie; Sleep(5); end;
    A := TJSONObject.Create; A.AddPair('id',Host.Editor.Movie.Project.Cues[0].Id); A.AddPair('acting',ParseObject('{"bodyGain":0.7}')); Run('update-cue',A.ToJSON,True); A.Free;
    Check(SameValue(Host.Editor.Movie.Project.Cues[0].Acting.MouthGain,0.6) and SameValue(Host.Editor.Movie.Project.Cues[0].Acting.BodyGain,0.7),'pipe partial acting update preserves omitted fields');
    Run('undo','{}',True); Check(Host.Editor.Movie.Project.Cues[0].Acting.BodyGain=1,'undo restores acting fields');
    Run('redo','{}',True); Check(SameValue(Host.Editor.Movie.Project.Cues[0].Acting.BodyGain,0.7),'redo reapplies acting fields');
    var RevisionBeforeBad := Host.Editor.Movie.Project.Revision; var BadActing := False;
    A := TJSONObject.Create; A.AddPair('id',Host.Editor.Movie.Project.Cues[0].Id); A.AddPair('acting',ParseObject('{"mouthGain":9}'));
    try try Run('update-cue',A.ToJSON,True); except BadActing := True; end; finally A.Free; end;
    Check(BadActing and (RevisionBeforeBad=Host.Editor.Movie.Project.Revision),'invalid acting rolls back project without partial revision');
    var Plot := TRigmMovieTimeline(Find(Studio,'MovieWaveTimeline')); Check((Plot.Width>100) and (Plot.Height>40),'waveform timeline has usable visible area');
    var Middle := Plot.HeaderWidthPixels+(Plot.Width-Plot.HeaderWidthPixels) div 2;
    Plot.Perform(WM_LBUTTONDOWN,MK_LBUTTON,MakeLParam(Middle,70)); Plot.Perform(WM_LBUTTONUP,0,MakeLParam(Middle,70));
    Check(Abs(Host.Editor.Movie.Time-0.8)<0.01,'waveform timeline click seeks spoken and subtitle clock together');
    var Zoom := TComboBox(Find(Studio,'MovieTimelineZoom')); Zoom.ItemIndex := 1; Zoom.OnChange(Zoom);
    Check(SameValue(Plot.SecondsAt(0),0) and SameValue(Plot.SecondsAt(Plot.Width),1.6),'timeline zoom clamps seek to actual project duration');
    Zoom.ItemIndex := 0; Zoom.OnChange(Zoom); Capture(Studio,'studio-acting-waveform');
    while Host.Editor.Movie.Busy or Studio.PreviewPending do begin Application.ProcessMessages; Host.Editor.PollMovie; Sleep(5); end;
    A := TJSONObject.Create; A.AddPair('path',TPath.Combine(Root,'acting.rigmovie')); Run('save',A.ToJSON); Run('open',A.ToJSON,True); A.Free;
    Check(SameValue(Host.Editor.Movie.Project.Cues[0].Acting.MouthGain,0.6) and SameValue(Host.Editor.Movie.Project.Cues[0].Acting.BodyGain,0.7),'save reopen persists per-cue acting');
    var ActingUiDeadline := GetTickCount64+2000;
    repeat Application.ProcessMessages; Sleep(5); until GetTickCount64>ActingUiDeadline;
    var SelectedActingCue := Host.Editor.Movie.Project.Cue(Plot.SelectedCueId);
    Check((SelectedActingCue<>nil) and (TEdit(Find(Studio,'MovieActing_mouthGain')).Text=FloatToStr(SelectedActingCue.Acting.MouthGain,TFormatSettings.Invariant)),
      'reopened acting UI represents the selected timeline cue');
    Plot.SelectCue(Host.Editor.Movie.Project.Cues[0].Id); Plot.OnSelectCue(Plot); Application.ProcessMessages;
    Check(TEdit(Find(Studio,'MovieActing_mouthGain')).Text='0.6','reopened acting values return to UI for editing');
    Path := TPath.Combine(Root,'portable.rigmovie'); A := TJSONObject.Create; A.AddPair('path',Path); Run('save',A.ToJSON); A.Free;
    Loaded := LoadMovie(Path);
    try
      Check(not TPath.IsPathRooted(Loaded.Cues[0].WaveFile),'saved audio uses portable relative asset paths');
      Check(Loaded.AudioReady(Loaded.Cues[0]),'saved project reopens ready speech asset references');
    finally Loaded.Free; end;
    var MovedDir := TPath.Combine(Root,'Moved'); ForceDirectories(MovedDir);
    A := TJSONObject.Create; A.AddPair('path',TPath.Combine(MovedDir,'renamed.rigmovie')); Run('save',A.ToJSON); A.Free;
    Loaded := LoadMovie(TPath.Combine(MovedDir,'renamed.rigmovie'));
    try Check(Loaded.AudioReady(Loaded.Cues[1]),'save-as rebases and copies assets into new folder'); finally Loaded.Free; end;
    A := TJSONObject.Create; AddN(A,'time',0.2); A.AddPair('path',TPath.Combine(Root,'worker-preview.png')); Run('preview',A.ToJSON); A.Free;
    O := Job; try Check(JS(O,'state')='succeeded','common pipe previews waveform lip-sync and subtitle frame: '+JS(O,'error')); finally O.Free; end;
    var UiDeadline := GetTickCount64+2000;
    while (TRigmMoviePreview(Find(Studio,'MoviePreviewImage')).Frame.Width<>640) and (GetTickCount64<UiDeadline) do begin Application.ProcessMessages; Sleep(5); end;
    Check(TRigmMoviePreview(Find(Studio,'MoviePreviewImage')).Frame.Width=640,'UI displays completed worker frame');
    TRigmMoviePreview(Find(Studio,'MoviePreviewImage')).Frame.SaveToFile(TPath.Combine(Root,'ui-preview.bmp'));
    var PreviewControl := Find(Studio,'MoviePreviewImage');
    Check((PreviewControl.Width>100) and (PreviewControl.Height>100) and PreviewControl.Visible,'preview viewport has a visible usable area');
    var PreviewBitmap := TRigmMoviePreview(PreviewControl).Frame; var White := 0;
    for var Y := PreviewBitmap.Height*80 div 100 to PreviewBitmap.Height*95 div 100 do begin
      var Row: PByte := PreviewBitmap.ScanLine[Y];
      for var X := 0 to PreviewBitmap.Width-1 do if (Row[X*4]>200) and (Row[X*4+1]>200) and (Row[X*4+2]>200) then Inc(White);
    end;
    Check(White>40,'worker GDI subtitle pixels are flushed before UI transfer');
    Capture(Studio,'studio-640'); Studio.Width := Studio.Constraints.MinWidth; Studio.Height := Studio.Constraints.MinHeight; Application.ProcessMessages; Capture(Studio,'studio-minimum');
    Check((GuideLabel.Width>500) and (GuideLabel.Height>=32) and (GuideLabel.Caption<>''),'guide remains visible at minimum supported width');
    Check(Find(Studio,'MovieApplyCue').Visible,'cue edits remain accessible at minimum layout'); Studio.Width := 1380; Studio.Height := 900;
    A := TJSONObject.Create; A.AddPair('path',TPath.Combine(Root,'workflow-tone.avi')); Run('export',A.ToJSON); A.Free;
    O := Job; try Check(JS(O,'state')='succeeded','common pipe exports complete audio video AVI on worker'); finally O.Free; end;
    Check(FileExists(TPath.Combine(Root,'workflow-tone.avi')),'completed export exists');
    A := TJSONObject.Create; A.AddPair('ffmpeg',FFmpegExe); Run('update-project',A.ToJSON,True); A.Free;
    A := TJSONObject.Create; A.AddPair('path',TPath.Combine(Root,'workflow-tone.mp4')); Run('export',A.ToJSON); A.Free;
    O := Job; try Check(JS(O,'state')='succeeded','existing FFmpeg exports H264 AAC MP4 without install or shell'); finally O.Free; end;
    var ExistingHash := THashSHA2.GetHashStringFromFile(TPath.Combine(Root,'workflow-tone.mp4'));
    A := TJSONObject.Create; A.AddPair('path',TPath.Combine(Root,'workflow-tone.mp4')); Run('export',A.ToJSON); A.Free;
    O := Job; try Check(JS(O,'state')='failed','existing output is refused'); finally O.Free; end;
    Check(THashSHA2.GetHashStringFromFile(TPath.Combine(Root,'workflow-tone.mp4'))=ExistingHash,'export rejection preserves existing output bytes');
    Run('update-project','{"outputPreset":"fullhd","encodeProfile":"quality"}',True);
    A := TJSONObject.Create; A.AddPair('id',Host.Editor.Movie.Project.Cues[0].Id); AddN(A,'pause',10); Run('update-cue',A.ToJSON,True); A.Free;
    var CancelPath := TPath.Combine(Root,'cancel-render.mp4'); A := TJSONObject.Create; A.AddPair('path',CancelPath); Run('export',A.ToJSON); A.Free;
    var CancelDeadline := GetTickCount64+10000; var SawRender: Boolean;
    repeat O := Call('job-status'); SawRender := (JS(O,'phase')='render') and (JN(O,'phaseCompleted')>2); O.Free;
      Application.ProcessMessages; Sleep(5); until SawRender or (GetTickCount64>CancelDeadline);
    Check(SawRender,'cancel test reaches actual full HD rendering');
    var StatusDeadline := GetTickCount64+2000;
    while not Find(Studio,'MovieJobProgress').Visible and (GetTickCount64<StatusDeadline) do begin Application.ProcessMessages; Sleep(5); end;
    O := Call('job-status');
    try Check(Find(Studio,'MovieJobProgress').Visible and not Find(Studio,'MovieStatus').Visible and (JN(O,'phaseTotal')>0),
      'manual export retains phase progress while the removed status rows remain hidden'); finally O.Free; end;
    Studio.InvokeAction(9); O := Job;
    try Check(JS(O,'state')='cancelled','cancel icon ends rendering job'); finally O.Free; end;
    Check(not FileExists(CancelPath) and (Length(TDirectory.GetFiles(Root,'cancel-render.mp4.*'))=0),'render cancellation cleans staging and leaves no partial final output');
    CancelPath := TPath.Combine(Root,'cancel-encode.mp4'); A := TJSONObject.Create; A.AddPair('path',CancelPath); Run('export',A.ToJSON); A.Free;
    CancelDeadline := GetTickCount64+30000; var ChildHandle: THandle := 0;
    repeat O := Call('job-status'); var ChildPid := JI(O,'encoderProcessId');
      if (JS(O,'phase')='encode') and (ChildPid>0) and not JB(O,'done') then ChildHandle := OpenProcess(SYNCHRONIZE,False,ChildPid);
      O.Free; Application.ProcessMessages; Sleep(5); until (ChildHandle<>0) or (GetTickCount64>CancelDeadline);
    Check(ChildHandle<>0,'encode cancel test opens handle to this job FFmpeg child');
    try
      TFile.WriteAllText(CancelPath,'protected concurrent output'); var ProtectedHash := THashSHA2.GetHashStringFromFile(CancelPath);
      var EncoderCancelAt := GetTickCount64; Run('job-cancel'); O := Job;
      try
        Check((JS(O,'state')='cancelled') and JB(O,'encoderExited'),'common pipe cancellation reports exited encoder child');
        AddN(O,'observedCancelMs',GetTickCount64-EncoderCancelAt); TFile.WriteAllText(TPath.Combine(Root,'encoder-cancel.json'),O.ToJSON,TEncoding.UTF8);
      finally O.Free; end;
      Check(WaitForSingleObject(ChildHandle,0)=WAIT_OBJECT_0,'cancelled own FFmpeg process has actually exited');
      Check((THashSHA2.GetHashStringFromFile(CancelPath)=ProtectedHash) and (Length(TDirectory.GetFiles(Root,'cancel-encode.mp4.*'))=0),'encode cancellation preserves concurrent existing output and cleans every own temporary');
    finally CloseHandle(ChildHandle); end;
    var RememberedTime := 0.0; var Recent := AppSettings.Recent;
    try for var V in Recent do if SameText(JS(TJSONObject(V),'path'),TPath.Combine(MovedDir,'renamed.rigmovie')) then RememberedTime := JN(TJSONObject(V),'time'); finally Recent.Free; end;
    A := TJSONObject.Create; A.AddPair('path',TPath.Combine(MovedDir,'renamed.rigmovie')); Run('open',A.ToJSON,True); A.Free;
    Check(not Host.Editor.Movie.Project.Modified,'open restores clean saved production state');
    Check(Host.Editor.Movie.Project.AudioReady(Host.Editor.Movie.Project.Cues[1]),'open restores copied asset cache and exact timeline');
    Check(not Host.Editor.Movie.Playing and (Host.Editor.Movie.Time=0),'open starts at zero without starting sound');
    Run('playback-audio','{"time":0.3}'); O := Job;
    try var Pcm := TRigmPcm.Load(JS(O,'output')); try Check(SameValue(Pcm.Duration,1.3),'preview audio seek trims same PCM clock at exact offset'); finally Pcm.Free; end; finally O.Free; end;
    C := Host.Editor.Movie.Project.Cues[0]; A := TJSONObject.Create; A.AddPair('id',C.Id); A.AddPair('text','変更したセリフ'); Run('update-cue',A.ToJSON,True); A.Free;
    Check(not Host.Editor.Movie.Project.AudioReady(Host.Editor.Movie.Project.Cues[0]),'pipe dialogue edit invalidates only its cached audio');
    Check(Host.Editor.Movie.Project.AudioReady(Host.Editor.Movie.Project.Cues[1]),'other cue audio remains ready');
    var Signal := TPath.Combine(FixtureDirectory,'synthesis-active.txt'); if FileExists(Signal) then TFile.Delete(Signal);
    TFile.WriteAllText(TPath.Combine(FixtureDirectory,'delay-ms.txt'),'1500'); Run('audio-generate');
    var Deadline := GetTickCount64+10000;
    while not FileExists(Signal) and (GetTickCount64<Deadline) do begin Application.ProcessMessages; Sleep(5); end;
    Check(FileExists(Signal),'cancellation test reaches active synthesis HTTP request');
    var CancelTime := GetTickCount64; Run('job-cancel'); var CancelCommandMs := LastPipeReplyMs; O := Job;
    var CancelTotalMs := GetTickCount64-CancelTime;
    var CancelMetrics := TJSONObject.Create;
    try AddN(CancelMetrics,'commandMs',CancelCommandMs); AddN(CancelMetrics,'totalMs',CancelTotalMs);
      AddN(CancelMetrics,'fixtureDelayMs',1500); CancelMetrics.AddPair('job',O.Clone as TJSONObject);
      TFile.WriteAllText(TPath.Combine(Root,'cancel-metrics.json'),CancelMetrics.ToJSON,TEncoding.UTF8);
    finally CancelMetrics.Free; end;
    Writeln('MEASURE cancellation reply=',CancelCommandMs,'ms UI-drain=',CancelTotalMs,'ms native=',JI(O,'cancelCallMs'),'ms worker=',JI(O,'cancelWorkerMs'),'ms');
    var CancelWorkerMs := JI(O,'cancelWorkerMs');
    try Check(JS(O,'state')='cancelled','active HTTP generation cancels without blocking UI'); finally O.Free; end;
    Check(CancelCommandMs<200,'cancel command returns without blocking UI');
    Check(CancelWorkerMs<800,'active request cancellation completes before delayed synthesis response');
    Check(CancelTotalMs<800,'cancel including queued UI processing retains original 800ms bound');
    for var Attempt := 2 to 3 do begin
      TFile.WriteAllText(TPath.Combine(FixtureDirectory,'delay-ms.txt'),'120'); Run('job-retry'); O := Job; O.Free;
      A := TJSONObject.Create; A.AddPair('id',Host.Editor.Movie.Project.Cues[0].Id); A.AddPair('text','取消計測 '+Attempt.ToString); Run('update-cue',A.ToJSON,True); A.Free;
      if FileExists(Signal) then TFile.Delete(Signal);
      TFile.WriteAllText(TPath.Combine(FixtureDirectory,'delay-ms.txt'),'1500'); Run('audio-generate'); Deadline := GetTickCount64+10000;
      while not FileExists(Signal) and (GetTickCount64<Deadline) do begin Application.ProcessMessages; Sleep(5); end;
      Check(FileExists(Signal),'repeated cancellation reaches active synthesis '+Attempt.ToString);
      CancelTime := GetTickCount64; Run('job-cancel'); CancelCommandMs := LastPipeReplyMs; O := Job; CancelTotalMs := GetTickCount64-CancelTime;
      Writeln('MEASURE cancellation attempt=',Attempt,' reply=',CancelCommandMs,'ms UI-drain=',CancelTotalMs,'ms native=',JI(O,'cancelCallMs'),'ms worker=',JI(O,'cancelWorkerMs'),'ms');
      var M := TJSONObject.Create; try AddN(M,'commandMs',CancelCommandMs); AddN(M,'totalMs',CancelTotalMs); AddN(M,'fixtureDelayMs',1500);
        M.AddPair('job',O.Clone as TJSONObject); TFile.WriteAllText(TPath.Combine(Root,'cancel-metrics-'+Attempt.ToString+'.json'),M.ToJSON,TEncoding.UTF8);
      finally M.Free; end;
      try Check((JS(O,'state')='cancelled') and (CancelCommandMs<200) and (JI(O,'cancelCallMs')<200) and (JI(O,'cancelWorkerMs')<800) and (CancelTotalMs<800),'repeated HTTP cancellation maintains original latency criteria '+Attempt.ToString); finally O.Free; end;
    end;
    TFile.WriteAllText(TPath.Combine(FixtureDirectory,'delay-ms.txt'),'120');
    Run('job-retry'); O := Job;
    try Check((JS(O,'state')='succeeded') and (JS(O,'kind')='audio'),'cancelled audio job retries using current script'); finally O.Free; end;
    Check(Host.Editor.Movie.Project.AudioReady(Host.Editor.Movie.Project.Cues[0]),'retry merges fresh audio into reopened saved project');
    Check(TPath.IsPathRooted(Host.Editor.Movie.Project.Cues[0].WaveFile),'default generated asset directory is canonical absolute path');
    C := Host.Editor.Movie.Project.Cues[0]; A := TJSONObject.Create; A.AddPair('id',C.Id); A.AddPair('text','取消直後の再試行'); Run('update-cue',A.ToJSON,True); A.Free;
    Run('audio-generate'); Run('job-cancel'); Run('job-retry'); O := Job;
    try
      TFile.WriteAllText(TPath.Combine(Root,'retry-job.json'),O.ToJSON,TEncoding.UTF8);
      Check((JS(O,'state')='succeeded') and (JS(O,'kind')='audio'),'retry immediately after cancel runs once after worker cleanup');
    finally O.Free; end;
    var LongCaption := StringOfChar('あ',140)+'これは長い日本語字幕の末尾です。';
    C := Host.Editor.Movie.Project.Cues[0]; A := TJSONObject.Create; A.AddPair('id',C.Id); A.AddPair('subtitle',LongCaption); Run('update-cue',A.ToJSON,True); A.Free;
    A := Host.Editor.Movie.Project.Json;
    try A.AddPair('actualFingerprint',Host.Editor.Movie.Project.AudioFingerprint(Host.Editor.Movie.Project.Cues[0])); TFile.WriteAllText(TPath.Combine(Root,'subtitle-cache.json'),A.ToJSON,TEncoding.UTF8); finally A.Free; end;
    Check(Host.Editor.Movie.Project.AudioReady(Host.Editor.Movie.Project.Cues[0]),'long subtitle update preserves actual audio');
    Run('preview','{"time":0.01}'); O := Job; O.Free; Application.ProcessMessages; Capture(Studio,'studio-long-subtitle');
    var FrameA := Host.Editor.Movie.TakeFrame; FrameA.Free;
    C := Host.Editor.Movie.Project.Cues[1]; A := TJSONObject.Create; A.AddPair('id',C.Id); A.AddPair('background',TPath.Combine(Root,'missing.png')); Run('update-cue',A.ToJSON,True); A.Free;
    Run('preview','{"time":1.0}'); O := Job;
    try Check(JS(O,'state')='failed','missing background returns explicit failed preview job'); finally O.Free; end;
    A := TJSONObject.Create; A.AddPair('id',Host.Editor.Movie.Project.Cues[1].Id); A.AddPair('background',''); Run('update-cue',A.ToJSON,True); A.Free;
    Run('job-retry'); O := Job; try Check(JS(O,'state')='succeeded','asset correction allows latest snapshot preview retry'); finally O.Free; end;
    var OldWave := Host.Editor.Movie.Project.Cues[1].WaveFile;
    var OldKey := Host.Editor.Movie.Project.Cues[1].AudioKey;
    var OldWaveHash := THashSHA2.GetHashStringFromFile(ResolveMoviePath(Host.Editor.Movie.Project.FileName,OldWave));
    for var I := 0 to 1 do begin
      A := TJSONObject.Create; A.AddPair('id',Host.Editor.Movie.Project.Cues[I].Id); A.AddPair('text','部分失敗の検証'+I.ToString); Run('update-cue',A.ToJSON,True); A.Free;
    end;
    TFile.WriteAllText(TPath.Combine(FixtureDirectory,'synthesis-count.txt'),'0');
    TFile.WriteAllText(TPath.Combine(FixtureDirectory,'fail-synthesis-number.txt'),'2'); Run('audio-generate'); O := Job;
    try Check(JS(O,'state')='failed','later synthesis failure is reported after partial successful cue'); finally O.Free; end;
    Check(Host.Editor.Movie.Project.AudioReady(Host.Editor.Movie.Project.Cues[0]),'partial successful audio remains usable after later cue failure');
    Check((Host.Editor.Movie.Project.Cues[1].WaveFile=OldWave) and (Host.Editor.Movie.Project.Cues[1].AudioKey=OldKey),'failed synthesis preserves prior cue asset reference and fingerprint');
    Check(THashSHA2.GetHashStringFromFile(ResolveMoviePath(Host.Editor.Movie.Project.FileName,OldWave))=OldWaveHash,'failed synthesis leaves prior WAV bytes unchanged');
    TFile.Delete(TPath.Combine(FixtureDirectory,'fail-synthesis-number.txt')); Run('job-retry'); O := Job;
    try Check(JS(O,'state')='succeeded','partial failure retry generates remaining missing audio'); finally O.Free; end;
    Check(StrToInt(Trim(TFile.ReadAllText(TPath.Combine(FixtureDirectory,'synthesis-count.txt'))))=3,'retry skips already successful cue and synthesizes one remaining cue');
    A := TJSONObject.Create; A.AddPair('id',Host.Editor.Movie.Project.Cues[0].Id); A.AddPair('text','古いスナップショット'); Run('update-cue',A.ToJSON,True); A.Free;
    OldWave := Host.Editor.Movie.Project.Cues[0].WaveFile; OldKey := Host.Editor.Movie.Project.Cues[0].AudioKey;
    if FileExists(Signal) then TFile.Delete(Signal);
    TFile.WriteAllText(TPath.Combine(FixtureDirectory,'delay-ms.txt'),'1500'); Run('audio-generate');
    Deadline := GetTickCount64+10000;
    while not FileExists(Signal) and (GetTickCount64<Deadline) do begin Application.ProcessMessages; Sleep(5); end;
    Check(FileExists(Signal) and Host.Editor.Movie.Busy,'stale fingerprint test changes owner during active synthesis');
    // The fixture gate ensures the snapshot has not already completed during pipe/UI dispatch.
    Host.Editor.Movie.Project.Cues[0].Text := 'より新しい編集'; Host.Editor.Movie.Project.Changed;
    O := Job; try Check(JS(O,'state')='succeeded','isolated old audio snapshot finishes independently'); finally O.Free; end;
    Check((Host.Editor.Movie.Project.Cues[0].Text='より新しい編集') and (Host.Editor.Movie.Project.Cues[0].WaveFile=OldWave) and (Host.Editor.Movie.Project.Cues[0].AudioKey=OldKey),'old fingerprint result cannot overwrite newer script or existing audio');
    TFile.WriteAllText(TPath.Combine(FixtureDirectory,'delay-ms.txt'),'120'); Run('job-retry'); O := Job; O.Free;
    Check(Host.Editor.Movie.Project.AudioReady(Host.Editor.Movie.Project.Cues[0]),'retry snapshots the latest owner-side script');
    A := TJSONObject.Create; A.AddPair('id',Host.Editor.Movie.Project.Cues[0].Id); A.AddPair('text','プロジェクト識別子の境界'); Run('update-cue',A.ToJSON,True); A.Free;
    OldWave := Host.Editor.Movie.Project.Cues[0].WaveFile;
    if FileExists(Signal) then TFile.Delete(Signal);
    TFile.WriteAllText(TPath.Combine(FixtureDirectory,'delay-ms.txt'),'1500'); Run('audio-generate');
    Deadline := GetTickCount64+10000;
    while not FileExists(Signal) and (GetTickCount64<Deadline) do begin Application.ProcessMessages; Sleep(5); end;
    Check(FileExists(Signal) and Host.Editor.Movie.Busy,'stale project test changes owner during active synthesis');
    Host.Editor.Movie.Project.Id := NewRigmId; Host.Editor.Movie.Project.Changed;
    O := Job; O.Free;
    Check(Host.Editor.Movie.Project.Cues[0].WaveFile=OldWave,'old project ID result cannot enter another production project');
    TFile.WriteAllText(TPath.Combine(FixtureDirectory,'delay-ms.txt'),'120');
    Run('job-retry'); O := Job; O.Free;
    Check(Host.Editor.Movie.Project.AudioReady(Host.Editor.Movie.Project.Cues[0]),'retry binds generated audio to current production project ID');
    A := TJSONObject.Create; A.AddPair('path',TPath.Combine(Root,'resume.rigmovie')); Run('save',A.ToJSON); A.Free;
    Run('preview','{"time":0.2}'); O := Job; O.Free;
    A := TJSONObject.Create; A.AddPair('path',TPath.Combine(Root,'resume.rigmovie')); Run('open',A.ToJSON,True); A.Free;
    var Rejected := False;
    try Run('job-retry'); except Rejected := True; end;
    Check(Rejected,'open clears previous project job so stale retry is refused');
    Run('seek','{"time":0.2}'); Run('play'); var PlayDeadline := GetTickCount64+3000;
    while (Host.Editor.Movie.Time<=0.25) and (GetTickCount64<PlayDeadline) do begin Application.ProcessMessages; Sleep(5); end;
    Check(Host.Editor.Movie.Time>0.25,'production UI playback advances from requested audio clock');
    Run('pause'); Application.ProcessMessages; var PausedTime := Host.Editor.Movie.Time;
    PlayDeadline := GetTickCount64+120; while GetTickCount64<PlayDeadline do begin Application.ProcessMessages; Sleep(5); end;
    Check(not Host.Editor.Movie.Playing and SameValue(Host.Editor.Movie.Time,PausedTime),'pause stops preview clock and sound preparation');
    while Host.Editor.Movie.Busy or Studio.PreviewPending do begin Application.ProcessMessages; Host.Editor.PollMovie; Sleep(5); end;
    A := Host.Editor.Movie.Project.Json; A.RemovePair('width').Free; AddN(A,'width',800);
    A.RemovePair('fps').Free; AddN(A,'fps',17); A.RemovePair('character').Free; A.AddPair('character','@sample');
    O := TJSONObject.Create; O.AddPair('format','json'); O.AddPair('text',A.ToJSON); Run('import-script',O.ToJSON,True); A.Free; O.Free;
    Check((Host.Editor.Movie.Project.Width=800) and (Host.Editor.Movie.Project.Fps=17),'JSON import honors explicitly authored dimensions and frame rate');
    Check(Host.Editor.Movie.Project.Speakers[0].Speed=1.1,'JSON import preserves authored speaker settings');
    var VariantDoc := Host.Editor.Document.Clone; var VariantPath := TPath.Combine(Root,'existing-variant-fixture.rigm');
    var GroupId,PartId: string;
    try
      var Mouth: TArtLayer := nil; for var L in VariantDoc.Layers do if VariantDoc.Part(L.Id).Role='mouth' then Mouth := L;
      var Group := VariantDoc.Art.AddLayer(alkGroup,'保存済み口素材',Mouth.Bounds); VariantDoc.SyncParts; VariantDoc.ReparentLayer(Mouth.Id,Group.Id,0);
      var Alternate := VariantDoc.Art.AddLayer(alkImage,'実在する試験口候補',Mouth.Bounds); Alternate.Pixels := Copy(Mouth.Pixels);
      for var I := 0 to Length(Alternate.Pixels) div 4-1 do Alternate.Pixels[I*4] := 250;
      Alternate.Visible := False; VariantDoc.SyncParts; VariantDoc.Part(Alternate.Id).Role := 'mouth'; VariantDoc.ReparentLayer(Alternate.Id,Group.Id,1);
      VariantDoc.Part(Alternate.Id).X := VariantDoc.Part(Mouth.Id).X; VariantDoc.Part(Alternate.Id).Y := VariantDoc.Part(Mouth.Id).Y;
      VariantDoc.Part(Alternate.Id).BoneId := VariantDoc.Part(Mouth.Id).BoneId; VariantDoc.GenerateMesh(Alternate.Id,VariantDoc.Part(Alternate.Id).BoneId,3);
      VariantDoc.ReparentLayer(Group.Id,'',4); SaveRigm(VariantDoc,VariantPath); GroupId := Group.Id; PartId := Alternate.Id;
    finally VariantDoc.Free; end;
    var VariantHash := THashSHA2.GetHashStringFromFile(VariantPath);
    A := TJSONObject.Create; A.AddPair('character',VariantPath); Run('update-project',A.ToJSON,True); A.Free;
    var AssetsButton := TToolButton(Find(Studio,'MovieAssets')); AssetsButton.OnClick(AssetsButton); O := Job;
    try Check(JS(O,'state')='succeeded','asset icon reads actual saved RIGM groups'); finally O.Free; end;
    var Choices := TComboBox(Find(Studio,'MovieVariantPart')); UiDeadline := GetTickCount64+3000;
    while (Choices.Items.Count<>3) and (GetTickCount64<UiDeadline) do begin Application.ProcessMessages; Sleep(5); end;
    Check(Choices.Items.Count=3,'variant UI offers saved default and two existing children'); Choices.ItemIndex := 2;
    TButton(Find(Studio,'MovieApplyActing')).Click;
    Check((Host.Editor.Movie.Project.Cues[0].Acting.Variants.Count=1) and (JS(TJSONObject(Host.Editor.Movie.Project.Cues[0].Acting.Variants[0]),'partId')=PartId),'variant UI stores selected actual part ID');
    Application.ProcessMessages; while Host.Editor.Movie.Busy or Studio.PreviewPending do begin Application.ProcessMessages; Host.Editor.PollMovie; Sleep(5); end;
    Run('preview','{"time":0.1}'); O := Job;
    try Check(JS(O,'state')='succeeded','actual selected variant renders in common preview'); finally O.Free; end;
    Check(THashSHA2.GetHashStringFromFile(VariantPath)=VariantHash,'acting UI leaves original character asset bytes unchanged');
    A := TJSONObject.Create; A.AddPair('path',TPath.Combine(Root,'variant-acting.rigmovie')); Run('save',A.ToJSON); Run('open',A.ToJSON,True); A.Free;
    Check(JS(TJSONObject(Host.Editor.Movie.Project.Cues[0].Acting.Variants[0]),'groupId')=GroupId,'save reopen preserves actual variant group selection');
    A := TJSONObject.Create; A.AddPair('id',Host.Editor.Movie.Project.Cues[0].Id); A.AddPair('acting',ParseObject('{"variants":[{"groupId":"'+GroupId+'","partId":"missing-part"}]}')); Run('update-cue',A.ToJSON,True); A.Free;
    Run('preview','{"time":0.1}'); O := Job; try Check(JS(O,'state')='failed','missing variant produces explicit failed preview instead of fabricated asset'); finally O.Free; end;
    TButton(Find(Studio,'MovieClearVariants')).Click; Check(Host.Editor.Movie.Project.Cues[0].Acting.Variants.Count=0,'variant clear UI restores saved character visibility');
    Application.ProcessMessages; while Host.Editor.Movie.Busy or Studio.PreviewPending do begin Application.ProcessMessages; Host.Editor.PollMovie; Sleep(5); end;
    Capture(Studio,'studio-variant-acting');
    ActingScroll.VertScrollBar.Position := 780; Capture(Studio,'studio-variant-controls'); ActingScroll.VertScrollBar.Position := 0;
    OldWave := Host.Editor.Movie.Project.Cues[0].WaveFile; OldKey := Host.Editor.Movie.Project.Cues[0].AudioKey;
    OldWaveHash := THashSHA2.GetHashStringFromFile(ResolveMoviePath(Host.Editor.Movie.Project.FileName,OldWave));
    Run('update-project','{"engineUrl":"http://127.0.0.1:65534"}',True); Run('audio-generate'); O := Job;
    try Check(JS(O,'state')='failed','missing engine audio job exposes actual failure'); finally O.Free; end;
    Check((Host.Editor.Movie.Project.Cues[0].WaveFile=OldWave) and (Host.Editor.Movie.Project.Cues[0].AudioKey=OldKey) and
      (THashSHA2.GetHashStringFromFile(ResolveMoviePath(Host.Editor.Movie.Project.FileName,OldWave))=OldWaveHash),'connection failure preserves all prior audio metadata and bytes');
    Run('diagnostics-refresh'); O := Diagnostic;
    try Check(not JB(JO(O,'engine'),'connected') and not JB(O,'realSpeechVerified'),'unavailable engine diagnosis reports actual connection failure without speech claim'); finally O.Free; end;
    var SavedTarget := TPath.Combine(Root,'guided-resume.avi'); A := TJSONObject.Create; A.AddPair('outputTarget',SavedTarget); Run('update-project',A.ToJSON,True); A.Free;
    var ResumePath := TPath.Combine(Root,'guided-resume.rigmovie'); A := TJSONObject.Create; A.AddPair('path',ResumePath); Run('save',A.ToJSON); Run('open',A.ToJSON,True); A.Free;
    Run('diagnostics-refresh'); O := Diagnostic;
    try Check(Host.Editor.Movie.Project.OutputTarget=SavedTarget,'diagnosis and reopen preserve saved production output target'); finally O.Free; end;
    var ResumeHash := THashSHA2.GetHashStringFromFile(ResumePath); O := Call('preparation'); O.Free;
    Check((THashSHA2.GetHashStringFromFile(ResumePath)=ResumeHash) and not Host.Editor.Movie.Project.Modified,'post-reopen diagnosis does not autosave or dirty saved project');
    TButton(Find(Studio,'MovieDiagnose')).Click; O := Diagnostic; O.Free; Capture(Studio,'studio-preparation-details');
    Check(TMemo(Find(Studio,'MoviePreparationDetails')).ReadOnly and (TMemo(Find(Studio,'MoviePreparationDetails')).Lines.Count>4),'diagnosis UI exposes read-only issues capabilities and estimates');
    Run('update-project','{"engineUrl":"http://127.0.0.1:51234","width":320,"height":180,"fps":10}',True);
    Run('diagnostics-refresh'); O := Diagnostic; O.Free;
    TButton(Find(Studio,'MovieReloadDraft')).Click; // Synchronize displayed settings before starting a new GUI edit.
    var GuidedTarget := TPath.Combine(Root,'next-step-tone.mp4'); TEdit(Find(Studio,'MovieOutputTarget')).Text := GuidedTarget;
    TButton(Find(Studio,'MovieApplySettings')).Click;
    SelectOwnedSavePath(FFmpegExe,procedure begin TToolButton(Find(Studio,'MovieFfmpeg')).Click; end);
    Check(Host.Editor.Movie.Project.FfmpegExe=FFmpegExe,'workflow GUI selects the actual existing FFmpeg executable through its native picker');
    O := Call('preparation');
    if JI(O,'audioPending')>0 then begin
      Check(JS(O,'nextAction')='movie-audio-generate','next-step guide routes pending real assets to audio generation');
      O.Free; TToolButton(Find(Studio,'MovieAudio')).Click; O := Job;
      Check(JS(O,'state')='succeeded','compatibility toolbar completes fixture audio generation');
    end;
    O.Free; O := Diagnostic;
    Check(JS(O,'nextAction')='movie-preview','ready audio guide routes to current preview before output'); O.Free;
    TToolButton(Find(Studio,'MoviePreview')).Click; O := Job;
    try Check(JS(O,'state')='succeeded','compatibility toolbar completes actual preview'); finally O.Free; end;
    O := Call('preparation'); try Check(JB(O,'canExport') and (JS(O,'nextAction')='movie-export'),'completed preview and new target advance guide to export'); finally O.Free; end;
    SelectOwnedSavePath(GuidedTarget,procedure begin TToolButton(Find(Studio,'MovieExport')).Click; end);
    Check(Host.Editor.Movie.Project.OutputTarget=GuidedTarget,'compatibility toolbar native save dialog applies the explicitly selected MP4 target');
    O := Job;
    try
      Check((JS(O,'state')='succeeded') and FileExists(GuidedTarget),'compatibility toolbar writes selected MP4 through the actual GUI save dialog');
      Check(JB(O,'collected') and JB(O,'encoderExited'),'GUI workflow MP4 export collects the job and encoder exit');
    finally O.Free; end;
    O := RigmManifest(Host.Editor.Document);
    try Check(THashSHA2.GetHashString(O.ToJSON)=SourceHash,'all movie operations preserve original RIGM bones meshes revision and unsaved state'); finally O.Free; end;
    Studio.Hide;
  finally Host.Free; end;
end;
begin
  Application.Initialize; TStyleManager.TrySetStyle('Windows Modern Dark'); Checks := TJSONArray.Create;
  for var I := 1 to ParamCount do begin
    if ParamStr(I).StartsWith('--fixture-dir=') then FixtureDirectory := ParamStr(I).Substring(14);
    if ParamStr(I).StartsWith('--ffmpeg=') then FFmpegExe := ParamStr(I).Substring(9);
  end;
  Root := TPath.Combine(ExtractFilePath(ParamStr(0)),'MovieWorkflow\'+FormatDateTime('yyyymmdd-hhnnss-zzz',Now)); ForceDirectories(Root);
  try
    try Tests; var O := TJSONObject.Create;
      try AddB(O,'success',True); AddN(O,'passed',Checks.Count); O.AddPair('directory',Root); O.AddPair('audioSource','deterministic test tone HTTP fixture, not VOICEVOX speech'); O.AddPair('checks',Checks.Clone as TJSONArray);
        TFile.WriteAllText(TPath.Combine(ExtractFilePath(ParamStr(0)),'movie-workflow-results.json'),O.ToJSON,TEncoding.UTF8);
      finally O.Free; end;
    except on E: Exception do begin
      var O := TJSONObject.Create;
      try AddB(O,'success',False); AddN(O,'partialPassed',Checks.Count); O.AddPair('error',E.Message); O.AddPair('directory',Root); O.AddPair('checks',Checks.Clone as TJSONArray);
        TFile.WriteAllText(TPath.Combine(ExtractFilePath(ParamStr(0)),'movie-workflow-results.json'),O.ToJSON,TEncoding.UTF8);
      finally O.Free; end;
      Writeln(E.ClassName+': '+E.Message); ExitCode := 1;
    end; end;
  finally Checks.Free; end;
end.
